"""initial migration

Revision ID: 9986bb344340
Revises: a89575e5e7fc
Create Date: 2018-08-12 23:42:37.003165

"""

# revision identifiers, used by Alembic.
revision = '9986bb344340'
down_revision = 'a89575e5e7fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('fromdate', sa.String(length=64), nullable=True))
    op.add_column('strategies', sa.Column('frommonth', sa.String(length=64), nullable=True))
    op.add_column('strategies', sa.Column('fromyear', sa.String(length=64), nullable=True))
    op.add_column('strategies', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('todate', sa.String(length=64), nullable=True))
    op.add_column('strategies', sa.Column('tomonth', sa.String(length=64), nullable=True))
    op.add_column('strategies', sa.Column('toyear', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'toyear')
    op.drop_column('strategies', 'tomonth')
    op.drop_column('strategies', 'todate')
    op.drop_column('strategies', 'stock')
    op.drop_column('strategies', 'fromyear')
    op.drop_column('strategies', 'frommonth')
    op.drop_column('strategies', 'fromdate')
    # ### end Alembic commands ###
