"""initial migration

Revision ID: a89575e5e7fc
Revises: 1aa5bf186669
Create Date: 2018-08-04 15:06:26.867416

"""

# revision identifiers, used by Alembic.
revision = 'a89575e5e7fc'
down_revision = '1aa5bf186669'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategies_strategyname', table_name='strategies')
    op.create_index(op.f('ix_strategies_strategyname'), 'strategies', ['strategyname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_strategyname'), table_name='strategies')
    op.create_index('ix_strategies_strategyname', 'strategies', ['strategyname'], unique=1)
    # ### end Alembic commands ###
