"""initial migration

Revision ID: d19b87be39d2
Revises: 9986bb344340
Create Date: 2018-08-13 16:39:39.794316

"""

# revision identifiers, used by Alembic.
revision = 'd19b87be39d2'
down_revision = '9986bb344340'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('enddate', sa.Date(), nullable=True))
    op.add_column('strategies', sa.Column('startdate', sa.Date(), nullable=True))
    op.drop_column('strategies', 'fromdate')
    op.drop_column('strategies', 'tomonth')
    op.drop_column('strategies', 'fromyear')
    op.drop_column('strategies', 'frommonth')
    op.drop_column('strategies', 'toyear')
    op.drop_column('strategies', 'todate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('todate', sa.VARCHAR(length=64), nullable=True))
    op.add_column('strategies', sa.Column('toyear', sa.VARCHAR(length=64), nullable=True))
    op.add_column('strategies', sa.Column('frommonth', sa.VARCHAR(length=64), nullable=True))
    op.add_column('strategies', sa.Column('fromyear', sa.VARCHAR(length=64), nullable=True))
    op.add_column('strategies', sa.Column('tomonth', sa.VARCHAR(length=64), nullable=True))
    op.add_column('strategies', sa.Column('fromdate', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('strategies', 'startdate')
    op.drop_column('strategies', 'enddate')
    # ### end Alembic commands ###
